# Generated by Django 3.1.3 on 2021-05-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0004_delete_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='imagen_informacion_general',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country'),
        ),
    ]
