# Generated by Django 3.1.3 on 2021-02-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0010_auto_20210227_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
    ]
