# Generated by Django 3.1.3 on 2021-03-02 23:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0013_auto_20210303_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='como_llegar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
