# Generated by Django 3.1.3 on 2021-03-24 16:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0015_auto_20210303_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='comida',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guide',
            name='imagen_informacion_general',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
