# Generated by Django 3.1.3 on 2021-04-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0019_producto_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
