# Generated by Django 3.1.3 on 2021-04-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0021_auto_20210403_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorproducto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
    ]
