# Generated by Django 3.1.3 on 2021-04-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0020_auto_20210403_0306'),
        ('descuentosApp', '0023_auto_20210403_1609'),
    ]

    operations = [
    ]
