# Generated by Django 3.1.3 on 2021-04-10 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_date_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_fin',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Fecha inválida', regex='[1-12]{1}/\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inicio',
            field=models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Fecha inválida', regex='[1-12]{1}/\\d{4}')]),
        ),
    ]
