# Generated by Django 3.1.3 on 2021-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210227_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_prefix',
        ),
    ]
