# Generated by Django 3.1.3 on 2021-03-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210303_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentType',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Au Pair'), ('3', 'Master'), ('4', 'Internship')], default='', max_length=10, null=True),
        ),
    ]
