# Generated by Django 3.1.3 on 2021-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20210327_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.IntegerField(default=34, null=True),
        ),
    ]
