# Generated by Django 3.1.3 on 2021-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_user_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.IntegerField(null=True),
        ),
    ]
