# Generated by Django 3.1.3 on 2021-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/'),
        ),
    ]
