# Generated by Django 3.1.3 on 2021-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210409_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto2',
            field=models.ImageField(blank=True, default='images/default2.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto3',
            field=models.ImageField(blank=True, default='images/default3.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto4',
            field=models.ImageField(blank=True, default='images/default4.png', null=True, upload_to='images/'),
        ),
    ]
