# Generated by Django 3.1.3 on 2021-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20210410_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=10.0),
        ),
    ]
