# Generated by Django 3.1.3 on 2021-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20210409_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
