# Generated by Django 3.1.3 on 2021-04-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20210409_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pedido',
            new_name='order',
        ),
    ]
