# Generated by Django 3.1.3 on 2021-04-14 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0017_auto_20210414_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pedido_de',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
