# Generated by Django 3.1.3 on 2021-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_auto_20210423_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='talla',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=10, null=True),
        ),
    ]
