# Generated by Django 3.1.3 on 2021-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_auto_20210423_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tallas',
            field=models.ManyToManyField(related_name='products', to='tienda.Tallas'),
        ),
    ]
