# Generated by Django 3.1.3 on 2021-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_auto_20210423_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
