# Generated by Django 3.1.3 on 2021-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0003_auto_20210227_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=34),
        ),
    ]
