# Generated by Django 3.1.3 on 2021-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0009_auto_20210227_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=30),
        ),
    ]
