# Generated by Django 3.1.3 on 2021-03-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0012_auto_20210227_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='body',
            new_name='informacion_general',
        ),
    ]
