# Generated by Django 3.1.3 on 2021-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0017_categoriaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('precio', models.IntegerField(default=10)),
                ('detalles', models.CharField(max_length=50, null=True)),
                ('bandera', models.CharField(max_length=20)),
                ('talla', models.CharField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL')], default='', max_length=10, null=True)),
                ('color', models.CharField(choices=[('1', 'Rojo'), ('2', 'Blanco'), ('3', 'Negro'), ('4', 'Azul')], default='', max_length=10, null=True)),
            ],
        ),
    ]
