# Generated by Django 3.1.3 on 2021-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0018_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Producto Erasmus Planet', max_length=30),
        ),
    ]
