# Generated by Django 3.1.3 on 2021-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0020_auto_20210403_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='bandera',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('1', 'XS'), ('2', 'S'), ('3', 'M'), ('4', 'L'), ('5', 'XL')], default='', max_length=10, null=True),
        ),
    ]
