# Generated by Django 3.1.3 on 2021-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210212_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cityDestination1',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityDestination2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityDestination3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='studies',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='universityDestination',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='universityOrigin',
            field=models.CharField(max_length=50),
        ),
    ]
