# Generated by Django 3.1.3 on 2021-03-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0013_auto_20210303_0030'),
        ('members', '0007_remove_user_phone_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default='SPAIN', on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country'),
        ),
    ]
