# Generated by Django 3.1.3 on 2021-04-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210410_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('Primero', '1'), ('Segundo', '2'), ('Tercero', '3'), ('Cuarto', '4'), ('Quinto', '5'), ('Sexto', '6')], default='', max_length=20),
        ),
    ]
