# Generated by Django 3.1.3 on 2021-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210411_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('Primero', '1'), ('Segundo', '2'), ('Tercero', '3'), ('Cuarto', '4'), ('Quinto', '5'), ('Sexto', '6')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_fin',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inicio',
            field=models.CharField(default='', max_length=8),
        ),
    ]
