# Generated by Django 3.1.3 on 2021-04-09 12:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('imagen_informacion_general', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('informacion_general', ckeditor.fields.RichTextField(blank=True)),
                ('como_llegar', ckeditor.fields.RichTextField(blank=True)),
                ('comida', ckeditor.fields.RichTextField(blank=True, default='')),
                ('alojamiento', ckeditor.fields.RichTextField(blank=True)),
                ('ocio', ckeditor.fields.RichTextField(blank=True)),
                ('divisas', ckeditor.fields.RichTextField(blank=True)),
                ('banco_sim', ckeditor.fields.RichTextField(blank=True)),
                ('donde_comprar', ckeditor.fields.RichTextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.province'),
        ),
    ]
