# Generated by Django 3.1.3 on 2021-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='foto',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto2',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto3',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto4',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto5',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto6',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='foto7',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
