# Generated by Django 3.1.3 on 2021-05-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0002_auto_20210425_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country'),
        ),
    ]
