# Generated by Django 3.1.3 on 2021-05-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0003_auto_20210509_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
