# Generated by Django 3.1.3 on 2020-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0003_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
