# Generated by Django 3.1.3 on 2020-11-29 21:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0005_auto_20201119_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
