# Generated by Django 3.1.3 on 2021-04-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_inicio',
            field=models.CharField(default='05/2021', max_length=7, validators=[django.core.validators.RegexValidator(message='Fecha inválida', regex='[1-12]{1}/\\d{4,}')]),
        ),
    ]
