# Generated by Django 3.1.3 on 2021-02-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0002_auto_20210212_1929'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cityOrigin1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='descuentosApp.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_prefix',
            field=models.CharField(blank=True, choices=[('Spain', '+34'), ('France', '+33'), ('Germany', '+49')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentType',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Au Pair'), ('3', 'Master'), ('4', 'Practices')], max_length=10, null=True),
        ),
    ]
