# Generated by Django 3.1.3 on 2021-02-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210212_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cityDestination1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityDestination2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityDestination3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Spain', 'Spain'), ('France', 'France'), ('Germany', 'Germany')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='universityDestination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='universityOrigin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
