# Generated by Django 3.1.3 on 2021-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210227_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_prefix',
            field=models.CharField(blank=True, choices=[('Spain', '+34'), ('France', '+33'), ('Germany', '+49')], max_length=10, null=True),
        ),
    ]
