# Generated by Django 3.1.3 on 2021-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0002_auto_20210212_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(default='SP', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='SP', max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=34, max_length=5),
        ),
    ]
