# Generated by Django 3.1.3 on 2021-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0007_auto_20210227_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default='34'),
        ),
    ]
