# Generated by Django 3.1.3 on 2021-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0008_auto_20210227_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(),
        ),
    ]
