# Generated by Django 3.1.3 on 2021-03-02 23:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentosApp', '0014_guide_como_llegar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='alojamiento',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='banco_sim',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='divisas',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='donde_comprar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='ocio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
